# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOeIU18K6lpkKqEGX7swuDi6_fghS8vl
"""

!pip install PyPDF2 beautifulsoup4 requests

import PyPDF2
import requests
from bs4 import BeautifulSoup
import os

def read_pdf(file_path):
    text = ""
    if not os.path.exists(file_path):
        return f"Error: File '{file_path}' not found."
    with open(file_path, "rb") as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            content = page.extract_text()
            if content:
                text += content
    return text

def scrape_website(url):
    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.text, "html.parser")
        paragraphs = soup.find_all("p")
        text = " ".join([p.get_text() for p in paragraphs])
        return text
    except:
        return ""

def extract_keywords(question):
    stopwords = ["how","to","is","the","a","an","of","for","in","on","what","why","explain","describe"]
    words = question.lower().split()
    return [word for word in words if word not in stopwords]

def chatbot_response(question, pdf_text, web_text):
    keywords = extract_keywords(question)

    for line in pdf_text.split("\n"):
        line = line.strip()
        if len(line) < 30:
            continue
        if any(keyword in line.lower() for keyword in keywords):
            return "ChatBot (From PDF):\n" + line

    for line in web_text.split("."):
        line = line.strip()
        if len(line) < 30:
            continue
        if any(keyword in line.lower() for keyword in keywords):
            return "ChatBot (From Website):\n" + line

    return "Sorry, no relevant instruction found."

# change to YOUR uploaded file name
pdf_path = "exp 3 2330172 ad lab.pdf"

pdf_text = read_pdf(pdf_path)
web_text = scrape_website("https://www.example.com")

print("Chatbot Ready")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        break
    print(chatbot_response(user_input, pdf_text, web_text))